[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aegis_onchain = "FPVw3tMxjARfaPFqkDRJSp19vPrzGQ1fW4oJwkUgeyxS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
