[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aegis_enforcer = "6tVnLWJmssXnTHRd98aho8w8XrUVYTzuiwcWwEtozwYG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
