import * as fs from 'fs';
import * as path from 'path';

// Read API Key natively
const envContent = fs.readFileSync(path.join(__dirname, '../.env'), 'utf-8');
const envMatch = envContent.match(/OPENROUTER_API_KEY=(.+)/);
const OPENROUTER_API_KEY = envMatch ? envMatch[1].trim() : null;

if (!OPENROUTER_API_KEY) {
    console.error("Missing OPENROUTER_API_KEY in environment variables.");
    process.exit(1);
}

// Extract targets 6-10 (Indices 5 to 9)
const triagePath = '/Users/user1000/.gemini/antigravity/brain/7f7d6692-e3a7-4eba-bc5a-e748ec55a6ae/frontier_triage.md';
const content = fs.readFileSync(triagePath, 'utf-8');
const bucketBStart = content.indexOf('## 🎯 BUCKET B: Prime Targets');
const bucketBContent = content.substring(bucketBStart);
const targets = bucketBContent.split('### Target ').slice(1);
const next5Targets = targets.slice(10).map(t => t.trim());

// The Trio
const MODELS = [
    { id: "x-ai/grok-4.3", name: "Grok 4.3" },
    { id: "anthropic/claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "deepseek/deepseek-r1", name: "DeepSeek R1" }
];

async function queryModel(modelId: string, systemPrompt: string, userPrompt: string) {
    const body = JSON.stringify({
        model: modelId,
        messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt }
        ]
    });

    try {
        const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${OPENROUTER_API_KEY}`,
                "HTTP-Referer": "https://aegis12.dev",
                "X-Title": "Aegis-12 Tri-Council",
                "Content-Type": "application/json"
            },
            body: body
        });

        if (!response.ok) {
            console.error(`[${modelId}] API Error: ${response.status} ${response.statusText}`);
            return `[FAILED: ${response.status}]`;
        }

        const data = await response.json();
        return data.choices[0].message.content;
    } catch (error) {
        console.error(`[${modelId}] Fetch error:`, error);
        return `[FAILED: Network Error]`;
    }
}

async function processTarget(targetDescription: string, index: number) {
    console.log(`\n================================`);
    console.log(`🚀 Processing Target ${index + 6}...`);
    
    const generatorPrompt = `You are an elite, seasoned technical sales executive for Aegis-12 (an x402 Active Policy Engine and TEE firewall on Solana/Phala). 
Read the following Colosseum hackathon project description. 
Your goal:
1) Identify exactly what they are building and why they are vulnerable to agent-liability or regulatory compliance issues.
2) Formulate a short, highly-humanized Discord DM (max 4 sentences) addressed to the builder.
3) It must be a 'win-win' (e.g., integrating our endpoint makes their architecture look hardware-secured and enterprise-ready to the judges).
4) It must include a subtle 'fear factor' (e.g. asking how they handle liability if an agent goes rogue or makes a sanctioned payment).
5) No emojis. No generic 'impressed with your work' slop. Speak builder-to-builder. Be direct.
6) Start your response with a 2-3 sentence internal reasoning on why you chose this specific angle, labeled "REASONING:", followed by the actual DM labeled "DM:".`;

    // MAP PHASE: Query all 3 models in parallel
    console.log(`[Map] Dispatching to Grok, Claude, and DeepSeek...`);
    const results = await Promise.all(MODELS.map(m => 
        queryModel(m.id, generatorPrompt, `Target Project Description:\n${targetDescription}`)
    ));

    const grokOutput = results[0];
    const claudeOutput = results[1];
    const deepseekOutput = results[2];

    // REDUCE PHASE: Consolidate
    console.log(`[Reduce] Synthesizing God-Tier DM with GPT-4o...`);
    const consolidatorPrompt = `You are the master sales strategist for Aegis-12. 
You are given three different outreach DMs generated by Grok, Claude, and DeepSeek.
Your job is to read all three, extract the best psychological hooks, the most precise technical observations, and merge them into the ultimate "God-Tier" DM.

Rules for the God-Tier DM:
1. Max 4 sentences.
2. Must mention Aegis-12 as an x402 Active Policy Engine running in a Phala TEE.
3. Must clearly state the win-win (integrating us gives them a hardware-secured compliance shield for the judges).
4. No emojis. Be ruthless, concise, and builder-to-builder.
5. Output ONLY the final DM text. Do not include reasoning or labels.`;

    const userPayload = `
    === GROK 4.3 OUTPUT ===
    ${grokOutput}
    
    === CLAUDE OPUS 4.7 OUTPUT ===
    ${claudeOutput}
    
    === DEEPSEEK R1 OUTPUT ===
    ${deepseekOutput}
    `;

    const godTierDM = await queryModel("openai/gpt-4o", consolidatorPrompt, userPayload);

    return {
        targetDescription,
        grokOutput,
        claudeOutput,
        deepseekOutput,
        godTierDM
    };
}

async function main() {
    let outputMd = `# Aegis-12 Veracity Trio: Multi-Model Synthesized DMs\n\n`;
    outputMd += `*This document contains the output of the Map-Reduce Tri-Council (Grok 4.3, Claude Opus 4.7, DeepSeek R1), synthesized into God-Tier DMs by GPT-4o.*\n\n---\n\n`;
    
    for (let i = 0; i < next5Targets.length; i++) {
        const data = await processTarget(next5Targets[i], i);
        
        outputMd += `## Target ${i + 11}\n`;
        outputMd += `**Original Pitch:**\n\`\`\`\n${data.targetDescription.substring(0, 300)}...\n\`\`\`\n\n`;
        
        outputMd += `### 👑 THE GOD-TIER DM (Synthesized)\n> ${data.godTierDM?.replace(/\n/g, '\n> ')}\n\n`;
        
        outputMd += `<details>\n<summary>View Raw Council Inputs (Grok, Claude, DeepSeek)</summary>\n\n`;
        outputMd += `#### Grok 4.3\n${data.grokOutput}\n\n`;
        outputMd += `#### Claude Opus 4.7\n${data.claudeOutput}\n\n`;
        outputMd += `#### DeepSeek R1\n${data.deepseekOutput}\n\n`;
        outputMd += `</details>\n\n---\n\n`;
    }

    const outputPath = '/Users/user1000/.gemini/antigravity/brain/7f7d6692-e3a7-4eba-bc5a-e748ec55a6ae/tri_council_dms_full.md';
    fs.writeFileSync(outputPath, outputMd);
    console.log(`\n✅ Tri-Council deliberation complete. DMs saved to: ${outputPath}`);
}

main();
