import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { AegisBatchProcessor } from '../../src/application/BatchProcessor';
import { AegisJournal } from '../../src/infrastructure/AegisJournal';
import { AegisSigner } from '../../src/infrastructure/AegisSigner';
import { AegisCanonicalMessage } from '../../src/types';
import * as fs from 'fs';
import * as path from 'path';

const journalPath = path.resolve(process.cwd(), '.aegis_test_batch_journal.log');
    let journal: AegisJournal;
    let signer: AegisSigner;
    let processor: AegisBatchProcessor;

    beforeEach(async () => {
        if (fs.existsSync(journalPath)) fs.unlinkSync(journalPath);
        journal = new AegisJournal(journalPath);
        signer = AegisSigner.createSync();
        processor = new AegisBatchProcessor(journal, signer);
    });

    afterEach(() => {
        if (fs.existsSync(journalPath)) fs.unlinkSync(journalPath);
    });

    it('should generate a Merkle root and PQ signature for a batch', async () => {
        // Add 3 transactions to the journal
        for (let i = 0; i < 3; i++) {
            journal.appendSync({
                tenantId: 't1',
                nonce: `n${i}`,
                article12LogHash: `hash${i}`,
                timestamp: `2026-04-21T12:00:0${i}Z`
            });
        }

        const batchCommitment = await processor.processBatch();
        
        expect(batchCommitment).toBeDefined();
        if (batchCommitment) {
            expect(batchCommitment.merkleRoot).toBeDefined();
            expect(batchCommitment.pqSignature).toBeDefined();
            // ML-DSA-65 signature is large
            expect(batchCommitment.pqSignature.length).toBeGreaterThan(6000);
            
            // Validate the signature was generated by the enclave's PQ key
            const isValid = signer.verifyMLDSA(batchCommitment.merkleRoot, batchCommitment.pqSignature, signer.getPQPublicKeyHex());
            expect(isValid).toBe(true);
            
            // Check proofs
            expect(Object.keys(batchCommitment.proofs).length).toBe(3);
            expect(batchCommitment.proofs['n0']).toBeDefined();
        }
    });

    it('should mark entries as batched in the journal', async () => {
        journal.appendSync({ tenantId: 't1', nonce: 'n1', article12LogHash: 'h1', timestamp: 't1' });
        
        await processor.processBatch();
        
        const unbatched = journal.getUnbatchedEntries();
        expect(unbatched.length).toBe(0);
    });

    it('should not process if there are no unbatched entries', async () => {
        const batchCommitment = await processor.processBatch();
        expect(batchCommitment).toBeNull();
    });
